CREATE TABLE CONDUCTOR 
    ( 
     ID_CONDUCTOR  NUMBER (5)  NOT NULL , 
     RUN_CONDUCTOR VARCHAR2 (12)  NOT NULL , 
     NOMBRE        VARCHAR2 (50)  NOT NULL , 
     APELLIDO      VARCHAR2 (50)  NOT NULL , 
     TELEFONO      VARCHAR2 (15) , 
     ID_SUCURSAL   NUMBER (3)  NOT NULL 
    ) 
;

ALTER TABLE CONDUCTOR 
    ADD CONSTRAINT PK_CONDUCTOR PRIMARY KEY ( ID_CONDUCTOR ) ;

ALTER TABLE CONDUCTOR 
    ADD CONSTRAINT CONDUCTOR__UN UNIQUE ( RUN_CONDUCTOR ) ;

CREATE TABLE DETALLE_ENVIO 
    ( 
     ID_ENVIO      NUMBER (6)  NOT NULL , 
     LINEA         NUMBER (3)  NOT NULL , 
     ID_TIPO_CARGA NUMBER (1)  NOT NULL , 
     PESO_KG       NUMBER (8,2)  NOT NULL , 
     VALOR_CARGA   NUMBER (10,2)  NOT NULL 
    ) 
;

ALTER TABLE DETALLE_ENVIO 
    ADD CONSTRAINT DETALLE_ENVIO_PK PRIMARY KEY ( ID_ENVIO, LINEA ) ;

CREATE TABLE ENVIO 
    ( 
     ID_ENVIO          NUMBER (6)  NOT NULL , 
     ID_RUTA           NUMBER (6)  NOT NULL , 
     FECHA_FACTURACION DATE  NOT NULL , 
     MONTO_TOTAL       NUMBER  NOT NULL , 
     ESTADO            VARCHAR2 (20)  NOT NULL 
    ) 
;

ALTER TABLE ENVIO 
    ADD CONSTRAINT PK_ENVIO PRIMARY KEY ( ID_ENVIO ) ;

CREATE TABLE MODELO_VEHICULO 
    ( 
     ID_MODELO  NUMBER (10)  NOT NULL , 
     NOM_MODELO VARCHAR2 (60)  NOT NULL 
    ) 
;

ALTER TABLE MODELO_VEHICULO 
    ADD CONSTRAINT MODELO_VEHICULO_PK PRIMARY KEY ( ID_MODELO ) ;

CREATE TABLE RUTA 
    ( 
     ID_RUTA                NUMBER (6)  NOT NULL , 
     ID_CONDUCTOR           NUMBER (5)  NOT NULL , 
     ID_VEHICULO            NUMBER  NOT NULL , 
     ID_SUCURSAL_ORIGEN     NUMBER (3)  NOT NULL , 
     ID_SUCURSAL_DESTINO    NUMBER (3)  NOT NULL , 
     FECHA_INICIO_RUTA      DATE , 
     FECHA_TERMINO_ESTIMADA DATE 
    ) 
;

ALTER TABLE RUTA 
    ADD CONSTRAINT PK_RUTA PRIMARY KEY ( ID_RUTA ) ;

CREATE TABLE SUCURSAL 
    ( 
     ID_SUCURSAL  NUMBER (3)  NOT NULL , 
     NOM_SUCURSAL VARCHAR2 (60)  NOT NULL 
    ) 
;

ALTER TABLE SUCURSAL 
    ADD CONSTRAINT PK_SUCURSAL PRIMARY KEY ( ID_SUCURSAL ) ;

CREATE TABLE TIPO_CARGA 
    ( 
     ID_TIPO_CARGA         NUMBER  NOT NULL , 
     NOM_TIPO_CARGA        VARCHAR2 (20)  NOT NULL , 
     TEMPERATURA_REQUERIDA VARCHAR2 (10) 
    ) 
;

ALTER TABLE TIPO_CARGA 
    ADD CONSTRAINT PK_TIPO_CARGA PRIMARY KEY ( ID_TIPO_CARGA ) ;

CREATE TABLE VEHICULO 
    ( 
     ID_VEHICULO        NUMBER  NOT NULL , 
     PATENTE            VARCHAR2 (10)  NOT NULL , 
     CAPACIDAD_CARGA_TN NUMBER (10)  NOT NULL , 
     ID_MODELO          NUMBER (10)  NOT NULL , 
     ID_TIPO_CARGA      NUMBER  NOT NULL 
    ) 
;

ALTER TABLE VEHICULO 
    ADD CONSTRAINT PK_VEHICULO PRIMARY KEY ( ID_VEHICULO ) ;

ALTER TABLE VEHICULO 
    ADD CONSTRAINT UN_VEHICULO_PATENTE UNIQUE ( PATENTE ) ;

ALTER TABLE DETALLE_ENVIO 
    ADD CONSTRAINT DETALLE_ENVIO_ENVIO_FK FOREIGN KEY 
    ( 
     ID_ENVIO
    ) 
    REFERENCES ENVIO 
    ( 
     ID_ENVIO
    ) 
;

ALTER TABLE CONDUCTOR 
    ADD CONSTRAINT FK_CONDUCTOR_SUCURSAL FOREIGN KEY 
    ( 
     ID_SUCURSAL
    ) 
    REFERENCES SUCURSAL 
    ( 
     ID_SUCURSAL
    ) 
;

ALTER TABLE ENVIO 
    ADD CONSTRAINT FK_ENVIO_RUTA FOREIGN KEY 
    ( 
     ID_RUTA
    ) 
    REFERENCES RUTA 
    ( 
     ID_RUTA
    ) 
;

ALTER TABLE RUTA 
    ADD CONSTRAINT FK_RUTA_CONDUCTOR FOREIGN KEY 
    ( 
     ID_CONDUCTOR
    ) 
    REFERENCES CONDUCTOR 
    ( 
     ID_CONDUCTOR
    ) 
;

ALTER TABLE RUTA 
    ADD CONSTRAINT FK_RUTA_VEHICULO FOREIGN KEY 
    ( 
     ID_VEHICULO
    ) 
    REFERENCES VEHICULO 
    ( 
     ID_VEHICULO
    ) 
;

ALTER TABLE VEHICULO 
    ADD CONSTRAINT VEHICULO_MODELO_VEHICULO_FK FOREIGN KEY 
    ( 
     ID_MODELO
    ) 
    REFERENCES MODELO_VEHICULO 
    ( 
     ID_MODELO
    ) 
;

ALTER TABLE VEHICULO 
    ADD CONSTRAINT VEHICULO_TIPO_CARGA_FK FOREIGN KEY 
    ( 
     ID_TIPO_CARGA
    ) 
    REFERENCES TIPO_CARGA 
    ( 
     ID_TIPO_CARGA
    ) 
;


