-- ================================================
-- SCRIPT PARA HLUO_ADMIN
-- EJERCICIO TIPO PRUEBA EV2
-- ================================================

-- 1. Cambiar al PDB (XEPDB1)
ALTER SESSION SET CONTAINER = XEPDB1;

-- 2. Crear usuario local
CREATE USER HLUO_ADMIN
IDENTIFIED BY "HLUO_ADMIN.practica.EV2" 
DEFAULT TABLESPACE "USERS" 
TEMPORARY TABLESPACE "TEMP";

-- 3. Asignar cuota
ALTER USER HLUO_ADMIN QUOTA UNLIMITED ON USERS;

-- 4. Otorgar permisos básicos
GRANT CREATE SESSION TO HLUO_ADMIN;
GRANT "RESOURCE" TO HLUO_ADMIN;
ALTER USER HLUO_ADMIN DEFAULT ROLE "RESOURCE";

GRANT CREATE TABLE TO HLUO_ADMIN;
GRANT ALTER ANY TABLE TO HLUO_ADMIN;
GRANT DROP ANY TABLE TO HLUO_ADMIN;
GRANT CREATE SEQUENCE TO HLUO_ADMIN;
GRANT CREATE INDEXTYPE TO HLUO_ADMIN;
GRANT CREATE SYNONYM TO HLUO_ADMIN;


-- 5. Verificar creación (opcional)
SELECT username, account_status, default_tablespace 
FROM dba_users 
WHERE username = 'MDY2131_P12';

-- ================================================
-- SCRIPT PARA HLUO_REPORT
-- EJERCICIO TIPO PRUEBA EV2
-- ================================================

-- 1. Cambiar al PDB (XEPDB1)
ALTER SESSION SET CONTAINER = XEPDB1;

-- 2. Crear usuario local
CREATE USER HLUO_REPORT
IDENTIFIED BY "HLUO_REPORT.practica.EV2" 
DEFAULT TABLESPACE "USERS" 
TEMPORARY TABLESPACE "TEMP";

-- 3. Asignar cuota
ALTER USER HLUO_REPORT QUOTA UNLIMITED ON USERS;

-- 4. Otorgar permisos básicos
GRANT CREATE SESSION TO HLUO_REPORT;
GRANT "RESOURCE" TO HLUO_REPORT;
ALTER USER HLUO_REPORT DEFAULT ROLE "RESOURCE";

GRANT CREATE PROCEDURE TO HLUO_REPORT;
GRANT CREATE MATERIALIZED VIEW TO HLUO_REPORT;

GRANT SELECT ON HLUO_ADMIN.AGENCIA                     TO HLUO_REPORT;
GRANT SELECT ON HLUO_ADMIN.CATEGORIA                   TO HLUO_REPORT;
GRANT SELECT ON HLUO_ADMIN.DETALLE_DIARIO_HUESPEDES    TO HLUO_REPORT;
GRANT SELECT ON HLUO_ADMIN.HUESPED                     TO HLUO_REPORT;
GRANT SELECT ON HLUO_ADMIN.HUESPED_TOUR                TO HLUO_REPORT;

GRANT UPDATE, INSERT, DELETE ON HLUO_ADMIN.AGENCIA                     TO HLUO_REPORT;
GRANT UPDATE, INSERT, DELETE ON HLUO_ADMIN.CATEGORIA                   TO HLUO_REPORT;
GRANT UPDATE, INSERT, DELETE ON HLUO_ADMIN.DETALLE_DIARIO_HUESPEDES    TO HLUO_REPORT;
GRANT UPDATE, INSERT, DELETE ON HLUO_ADMIN.HUESPED                     TO HLUO_REPORT;
GRANT UPDATE, INSERT, DELETE ON HLUO_ADMIN.HUESPED_TOUR                TO HLUO_REPORT;



-- 5. Verificar creación (opcional)
SELECT username, account_status, default_tablespace 
FROM dba_users 
WHERE username = 'HLUO_REPORT';