ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER MDY2131_P2 
IDENTIFIED BY "MDY2131.practica_p2" 
DEFAULT TABLESPACE USERS 
TEMPORARY TABLESPACE TEMP;

ALTER USER MDY2131_P2 QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO MDY2131_P2;
GRANT RESOURCE TO MDY2131_P2;
ALTER USER MDY2131_P2 DEFAULT ROLE RESOURCE;

-- Verificación
SELECT username, account_status, default_tablespace 
FROM dba_users 
WHERE username = 'MDY2131_P2';