
DROP TABLE DETALLE_ENVIO CASCADE CONSTRAINTS;
DROP TABLE ENVIO CASCADE CONSTRAINTS;
DROP TABLE RUTA CASCADE CONSTRAINTS;
DROP TABLE VEHICULO CASCADE CONSTRAINTS;
DROP TABLE CONDUCTOR CASCADE CONSTRAINTS;
DROP TABLE SUCURSAL CASCADE CONSTRAINTS;
DROP TABLE MODELO_VEHICULO CASCADE CONSTRAINTS;
DROP TABLE TIPO_CARGA CASCADE CONSTRAINTS;

-- Nota: La identificación de SUCURSALES (500, 50) se implementará directamente en la tabla con IDENTITY.

-- *******************************************************************
-- CREACIÓN Y AJUSTE DE TABLAS PREEXISTENTES (Dimensionales)
-- *******************************************************************

-- Tabla SUCURSAL (Requiere AUTO_INCREMENTABLE: 500, 50) [6]
CREATE TABLE SUCURSAL (
    ID_SUCURSAL NUMBER(3,0) NOT NULL,
    NOM_SUCURSAL VARCHAR2(60) NOT NULL
);
ALTER TABLE SUCURSAL ADD CONSTRAINT PK_SUCURSAL PRIMARY KEY (ID_SUCURSAL);

-- Tabla TIPO_CARGA (Similar a CATEGORIA)
CREATE TABLE TIPO_CARGA (
    ID_TIPO_CARGA NUMBER(1,0) NOT NULL,
    NOM_TIPO_CARGA VARCHAR2(20) NOT NULL,
    TEMPERATURA_REQUERIDA VARCHAR2(10) -- Ejemplo de atributo adicional
);
ALTER TABLE TIPO_CARGA ADD CONSTRAINT PK_TIPO_CARGA PRIMARY KEY (ID_TIPO_CARGA);

-- Tabla MODELO_VEHICULO (Similar a MARCA)
CREATE TABLE MODELO_VEHICULO (
    ID_MODELO NUMBER(4,0) NOT NULL,
    NOM_MODELO VARCHAR2(60) NOT NULL
);

-- *******************************************************************
-- CREACIÓN DE TABLAS OPERACIONALES (Requeridas)
-- *******************************************************************

-- Tabla CONDUCTOR (Similar a VENDEDOR o CLIENTE)
CREATE TABLE CONDUCTOR (
    ID_CONDUCTOR NUMBER(5,0) NOT NULL,
    RUN_CONDUCTOR VARCHAR2(12) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50) NOT NULL,
    TELEFONO VARCHAR2(15),
    ID_SUCURSAL NUMBER(3,0) NOT NULL -- Sucursal a la que está asociado el conductor
);
-- Restricciones de CONDUCTOR
ALTER TABLE CONDUCTOR ADD CONSTRAINT PK_CONDUCTOR PRIMARY KEY (ID_CONDUCTOR);
-- Regla de Negocio: El RUN del conductor debe ser único [7]
ALTER TABLE CONDUCTOR ADD CONSTRAINT FK_CONDUCTOR_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL);


-- Tabla VEHICULO (Necesita FK a MODELO_VEHICULO)
CREATE TABLE VEHICULO (
    ID_VEHICULO NUMBER(5,0) NOT NULL,
    PATENTE VARCHAR2(10) NOT NULL,
    CAPACIDAD_CARGA_TN NUMBER(5,2) NOT NULL, -- Capacidad en toneladas
    ID_MODELO NUMBER(4,0) NOT NULL
);
-- Restricciones de VEHICULO
ALTER TABLE VEHICULO ADD CONSTRAINT PK_VEHICULO PRIMARY KEY (ID_VEHICULO);
ALTER TABLE VEHICULO ADD CONSTRAINT UN_VEHICULO_PATENTE UNIQUE (PATENTE);
ALTER TABLE VEHICULO ADD CONSTRAINT FK_VEHICULO_MODELO FOREIGN KEY (ID_MODELO) REFERENCES MODELO_VEHICULO(ID_MODELO);

-- Tabla RUTA (Define un viaje específico asignado a un conductor y vehículo)
CREATE TABLE RUTA (
    ID_RUTA NUMBER(6,0) NOT NULL,
    ID_CONDUCTOR NUMBER(5,0) NOT NULL,
    ID_VEHICULO NUMBER(5,0) NOT NULL,
    ID_SUCURSAL_ORIGEN NUMBER(3,0) NOT NULL,
    ID_SUCURSAL_DESTINO NUMBER(3,0) NOT NULL,
    FECHA_INICIO_RUTA NUMBER,
    FECHA_TERMINO_ESTIMADA DATE
);
-- Restricciones de RUTA
ALTER TABLE RUTA ADD CONSTRAINT PK_RUTA PRIMARY KEY (ID_RUTA);
ALTER TABLE RUTA ADD CONSTRAINT FK_RUTA_CONDUCTOR FOREIGN KEY (ID_CONDUCTOR) REFERENCES CONDUCTOR(ID_CONDUCTOR);
ALTER TABLE RUTA ADD CONSTRAINT FK_RUTA_VEHICULO FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULO(ID_VEHICULO);

-- *******************************************************************
-- CREACIÓN DE TABLAS TRANSACCIONALES (Hechos / Normalización)
-- *******************************************************************

-- Tabla ENVIO (Encabezado de la transacción, utiliza la SECUENCIA)
CREATE TABLE ENVIO (
    ID_ENVIO NUMBER(6,0) NOT NULL, 
    ID_RUTA NUMBER(6,0) NOT NULL,
    FECHA_FACTURACION DATE NOT NULL,
    MONTO_TOTAL DATE NOT NULL,
    ESTADO VARCHAR2(20) NOT NULL -- EJ: 'Pendiente', 'En Curso', 'Entregado'
);
-- Restricciones de ENVIO
ALTER TABLE ENVIO ADD CONSTRAINT PK_ENVIO PRIMARY KEY (ID_ENVIO);
ALTER TABLE ENVIO ADD CONSTRAINT FK_ENVIO_RUTA FOREIGN KEY (ID_RUTA) REFERENCES RUTA(ID_RUTA);


-- Tabla DETALLE_ENVIO (Tabla necesaria para la normalización, separa los ítems de carga por envío) [7, 8]
CREATE TABLE DETALLE_ENVIO (
    ID_ENVIO NUMBER(6,0) NOT NULL,
    LINEA NUMBER(3,0) NOT NULL, -- Número de línea dentro del envío
    ID_TIPO_CARGA NUMBER(1,0) NOT NULL,
    PESO_KG NUMBER(8,2) NOT NULL,
    VALOR_CARGA NUMBER(10,2) NOT NULL
);

-- FIN DEL SCRIPT DE CREACIÓN