-- ================================================
-- SCRIPT PARA MDY2131_P11
-- ================================================

ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER MDY2131_P11
IDENTIFIED BY "MDY2131.practica_p11"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

ALTER USER MDY2131_P11
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO MDY2131_P11;
GRANT RESOURCE TO MDY2131_P11;

ALTER USER MDY2131_P11
DEFAULT ROLE RESOURCE;