/* Creación de usuario si está trabajando con BD Oracle XE */
CREATE USER BDY1102_FA IDENTIFIED BY "EVALUACION_1.practica2026"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_FA QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO BDY1102_FA;
GRANT "RESOURCE" TO BDY1102_FA;
ALTER USER BDY1102_FA DEFAULT ROLE "RESOURCE";


/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER BDY1102_FA IDENTIFIED BY "EVALUACION_1.practica2026"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_FA QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO BDY1102_FA;
GRANT "RESOURCE" TO BDY1102_FA;
ALTER USER BDY1102_FA DEFAULT ROLE "RESOURCE";