-- ============================================================================
-- BDY1102 - BASE DE DATOS APLICADA II
-- EVALUACION FINAL TRANSVERSAL - FORMA D
-- CASO: EVALUACION DE SOLICITUDES DE CREDITO HIPOTECARIO - BANCO AUSTRAL
-- Script de creacion de tablas: base_de_datos.sql
-- Ejecutar con el usuario BDY1102_ET_FD (dueño del modelo)
-- ============================================================================

DROP TABLE SOLICITUD_CREDITO CASCADE CONSTRAINTS;
DROP TABLE PROPIEDAD CASCADE CONSTRAINTS;
DROP TABLE PROYECTO_INMOBILIARIO CASCADE CONSTRAINTS;
DROP TABLE TIPO_PROPIEDAD CASCADE CONSTRAINTS;
DROP TABLE ANTECEDENTES_LABORALES CASCADE CONSTRAINTS;
DROP TABLE ANTECEDENTES_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE SUCURSAL CASCADE CONSTRAINTS;
DROP TABLE TIPO_TRABAJADOR CASCADE CONSTRAINTS;
DROP TABLE COMUNA CASCADE CONSTRAINTS;
DROP TABLE REGION CASCADE CONSTRAINTS;
DROP TABLE DETALLE_PUNTAJE_SOLICITUD CASCADE CONSTRAINTS;
DROP TABLE RESULTADO_SOLICITUD CASCADE CONSTRAINTS;
DROP TABLE PTJE_TIPO_TRABAJADOR CASCADE CONSTRAINTS;
DROP TABLE PTJE_ANNOS_ANTIGUEDAD CASCADE CONSTRAINTS;
DROP TABLE PTJE_TIPO_PROPIEDAD CASCADE CONSTRAINTS;
DROP TABLE ERROR_PROCESO;
DROP SEQUENCE SEQ_REGION;
DROP SEQUENCE SEQ_COMUNA;
DROP SEQUENCE SEQ_SUCURSAL;
DROP SEQUENCE SEQ_PROYECTO;
DROP SEQUENCE SEQ_PROPIEDAD;
DROP SEQUENCE SEQ_ERROR;

CREATE SEQUENCE SEQ_REGION;
CREATE SEQUENCE SEQ_COMUNA START WITH 100 INCREMENT BY 5;
CREATE SEQUENCE SEQ_SUCURSAL START WITH 500 INCREMENT BY 10;
CREATE SEQUENCE SEQ_PROYECTO START WITH 2000 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PROPIEDAD START WITH 10000 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ERROR;

CREATE TABLE REGION
(cod_region NUMBER(3) NOT NULL,
 nombre_region VARCHAR2(50) NOT NULL,
 CONSTRAINT PK_REGION PRIMARY KEY(cod_region));

CREATE TABLE COMUNA
(cod_comuna NUMBER(5) NOT NULL,
 nombre_comuna VARCHAR2(50) NOT NULL,
 cod_region NUMBER(3) NOT NULL,
 CONSTRAINT PK_COMUNA PRIMARY KEY(cod_comuna),
 CONSTRAINT FK_COMUNA_REGION FOREIGN KEY(cod_region) REFERENCES REGION(cod_region));

CREATE TABLE TIPO_TRABAJADOR
(cod_tipo_trab NUMBER(4) NOT NULL,
 desc_tipo_trab VARCHAR2(50) NOT NULL,
 CONSTRAINT PK_TIPO_TRABAJADOR PRIMARY KEY(cod_tipo_trab));

CREATE TABLE SUCURSAL
(cod_sucursal NUMBER(5) NOT NULL,
 nombre_sucursal VARCHAR2(60) NOT NULL,
 cod_comuna NUMBER(5) NOT NULL,
 CONSTRAINT PK_SUCURSAL PRIMARY KEY(cod_sucursal),
 CONSTRAINT FK_SUCURSAL_COMUNA FOREIGN KEY(cod_comuna) REFERENCES COMUNA(cod_comuna));

CREATE TABLE ANTECEDENTES_CLIENTE
(numrun NUMBER(8) NOT NULL,
 dvrun VARCHAR2(1) NOT NULL,
 pnombre VARCHAR2(15) NOT NULL,
 snombre VARCHAR2(15),
 apaterno VARCHAR2(15) NOT NULL,
 amaterno VARCHAR2(15) NOT NULL,
 fecha_nacimiento DATE NOT NULL,
 telefono_contacto NUMBER(11),
 cod_tipo_trab NUMBER(4) NOT NULL,
 cod_sucursal NUMBER(5) NOT NULL,
 CONSTRAINT PK_ANT_CLIENTE PRIMARY KEY(numrun),
 CONSTRAINT FK_ANT_CLI_TIPOTRAB FOREIGN KEY(cod_tipo_trab) REFERENCES TIPO_TRABAJADOR(cod_tipo_trab),
 CONSTRAINT FK_ANT_CLI_SUCURSAL FOREIGN KEY(cod_sucursal) REFERENCES SUCURSAL(cod_sucursal));

CREATE TABLE ANTECEDENTES_LABORALES
(numrun NUMBER(8) NOT NULL,
 fecha_contrato DATE NOT NULL,
 renta_mensual NUMBER(8) NOT NULL,
 nombre_empleador VARCHAR2(80) NOT NULL,
 cod_comuna NUMBER(5) NOT NULL,
 CONSTRAINT PK_ANT_LABORALES PRIMARY KEY(numrun, fecha_contrato),
 CONSTRAINT FK_ANT_LAB_ANT_CLI FOREIGN KEY(numrun) REFERENCES ANTECEDENTES_CLIENTE(numrun),
 CONSTRAINT FK_ANT_LAB_COMUNA FOREIGN KEY(cod_comuna) REFERENCES COMUNA(cod_comuna));

CREATE TABLE TIPO_PROPIEDAD
(cod_tipo_prop NUMBER(3) NOT NULL,
 desc_tipo_prop VARCHAR2(40) NOT NULL,
 CONSTRAINT PK_TIPO_PROPIEDAD PRIMARY KEY(cod_tipo_prop));

CREATE TABLE PROYECTO_INMOBILIARIO
(cod_proyecto NUMBER(4) NOT NULL,
 nombre_proyecto VARCHAR2(60) NOT NULL,
 cod_tipo_prop NUMBER(3) NOT NULL,
 cod_comuna NUMBER(5) NOT NULL,
 CONSTRAINT PK_PROY_INMOB PRIMARY KEY(cod_proyecto),
 CONSTRAINT FK_PROY_TIPOPROP FOREIGN KEY(cod_tipo_prop) REFERENCES TIPO_PROPIEDAD(cod_tipo_prop),
 CONSTRAINT FK_PROY_COMUNA FOREIGN KEY(cod_comuna) REFERENCES COMUNA(cod_comuna));

CREATE TABLE PROPIEDAD
(cod_propiedad NUMBER(7) NOT NULL,
 direccion VARCHAR2(120) NOT NULL,
 valor_uf NUMBER(8) NOT NULL,
 cod_proyecto NUMBER(4) NOT NULL,
 CONSTRAINT PK_PROPIEDAD PRIMARY KEY(cod_propiedad),
 CONSTRAINT FK_PROP_PROYECTO FOREIGN KEY(cod_proyecto) REFERENCES PROYECTO_INMOBILIARIO(cod_proyecto));

CREATE TABLE SOLICITUD_CREDITO
(numrun NUMBER(8) NOT NULL,
 cod_propiedad NUMBER(7) NOT NULL,
 fecha_solicitud DATE NOT NULL,
 plazo_annos NUMBER(2) NOT NULL,
 monto_credito_uf NUMBER(8) NOT NULL,
 CONSTRAINT PK_SOLICITUD_CRED PRIMARY KEY(numrun),
 CONSTRAINT FK_SOL_CRED_ANTCLI FOREIGN KEY(numrun) REFERENCES ANTECEDENTES_CLIENTE(numrun),
 CONSTRAINT FK_SOL_CRED_PROP FOREIGN KEY(cod_propiedad) REFERENCES PROPIEDAD(cod_propiedad));

CREATE TABLE DETALLE_PUNTAJE_SOLICITUD
(run_cliente VARCHAR2(13) NOT NULL,
 nombre_cliente VARCHAR2(60) NOT NULL,
 ptje_tipo_trabajador NUMBER(4) NOT NULL,
 ptje_antiguedad_lab NUMBER(4) NOT NULL,
 ptje_tipo_propiedad NUMBER(4) NOT NULL,
 ptje_extra NUMBER(4) NOT NULL);

CREATE TABLE RESULTADO_SOLICITUD
(run_cliente VARCHAR2(13) NOT NULL,
 ptje_final_sol NUMBER(6) NOT NULL,
 resultado_sol VARCHAR2(20) NOT NULL);

CREATE TABLE PTJE_TIPO_TRABAJADOR
(cod_tipo_trab NUMBER(4) NOT NULL,
 ptje_tipo_trab NUMBER(4) NOT NULL,
 CONSTRAINT PK_PTJE_TIPO_TRAB PRIMARY KEY(cod_tipo_trab));

CREATE TABLE PTJE_ANNOS_ANTIGUEDAD
(rango_annos_ini NUMBER(2) NOT NULL,
 rango_annos_ter NUMBER(2) NOT NULL,
 ptje_antiguedad NUMBER(4) NOT NULL,
 CONSTRAINT PK_PTJE_ANNOS_ANTIG PRIMARY KEY(rango_annos_ini));

CREATE TABLE PTJE_TIPO_PROPIEDAD
(cod_tipo_prop NUMBER(3) NOT NULL,
 ptje_tipo_prop NUMBER(4) NOT NULL,
 CONSTRAINT PK_PTJE_TIPO_PROP PRIMARY KEY(cod_tipo_prop));

CREATE TABLE ERROR_PROCESO
(id_error NUMBER(4) NOT NULL,
 rutina_error VARCHAR2(50) NOT NULL,
 descrip_error VARCHAR2(300) NOT NULL,
 CONSTRAINT PK_ERROR_PROCESO PRIMARY KEY(id_error));
