SELECT * FROM BDY1102_ET_FD.DETALLE_PUNTAJE_SOLICITUD;
SELECT * FROM BDY1102_ET_FD.RESULTADO_SOLICITUD;
SELECT * FROM BDY1102_ET_FD.ANTECEDENTES_CLIENTE;

EXPLAIN PLAN FOR
SELECT
  ac.APATERNO
  ,ac.AMATERNO
  ,ac.PNOMBRE || ' ' || ac.SNOMBRE AS "NOMBRE"
  ,rs.RUN_CLIENTE
  ,rs.PTJE_FINAL_SOL
  ,dps.PTJE_ANTIGUEDAD_LAB
  ,dps.PTJE_TIPO_PROPIEDAD
  ,dps.PTJE_TIPO_TRABAJADOR
  ,dps.PTJE_EXTRA
FROM BDY1102_ET_FD.RESULTADO_SOLICITUD rs
JOIN BDY1102_ET_FD.ANTECEDENTES_CLIENTE ac ON ac.numrun = rs.run_cliente
JOIN BDY1102_ET_FD.DETALLE_PUNTAJE_SOLICITUD dps ON dps.run_cliente = rs.RUN_CLIENTE
WHERE rs.PTJE_FINAL_SOL > (
  SELECT AVG(PTJE_FINAL_SOL) FROM BDY1102_ET_FD.RESULTADO_SOLICITUD
)
ORDER BY rs.PTJE_FINAL_SOL DESC
;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

CREATE INDEX IDX_RESULTADO_PTJE ON BDY1102_ET_FD.RESULTADO_SOLICITUD(PTJE_FINAL_SOL);
CREATE INDEX IDX_DETALLE_RUN ON BDY1102_ET_FD.DETALLE_PUNTAJE_SOLICITUD(RUN_CLIENTE);
;