--- Setup -------------------------------------

-- Crear contenedor y abrirlo
CREATE PLUGGABLE DATABASE XEPDB1
ADMIN USER admin_xepdb1 IDENTIFIED BY password
;

-- Cambiar al contendor PBD creado
ALTER SESSION SET CONTAINER = XEPDB1; -- FREEPDB1

-- Asignar archivo y espacio para usuarios
--CREATE TABLESPACE USERS DATAFILE 'users01.dbf' SIZE 100M AUTOEXTEND ON NEXT 50M;

--- Usuario: BDY1102_ET_FD ---------------------

-- BORRAR USUARIO:
--DROP USER BDY1102_ET_FD CASCADE;

CREATE USER BDY1102_ET_FD
IDENTIFIED BY "1234"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
;

-- Asignar cuota para el tablespace USERS
ALTER USER BDY1102_ET_FD QUOTA UNLIMITED ON USERS;

--- Permisos
-- Conexión a la DB
GRANT CREATE SESSION TO BDY1102_ET_FD;

-- Permisos del caso
GRANT CREATE TABLE TO BDY1102_ET_FD;
GRANT CREATE SEQUENCE TO BDY1102_ET_FD;
-- (Innecesario para crear índices en sus propias tablas)
GRANT CREATE ANY INDEX TO BDY1102_ET_FD;

-- IMPORTANTE:
-- Crear la conexión y luego crear y poblar las tablas antes de continuar

--- Rol de desarrollador ---------------------

CREATE ROLE ROL_DESARROLLADOR;

GRANT SELECT ON BDY1102_ET_FD.ANTECEDENTES_CLIENTE TO ROL_DESARROLLADOR;
GRANT SELECT ON BDY1102_ET_FD.ANTECEDENTES_LABORALES TO ROL_DESARROLLADOR;
GRANT SELECT ON BDY1102_ET_FD.COMUNA TO ROL_DESARROLLADOR;
GRANT SELECT ON BDY1102_ET_FD.PROPIEDAD TO ROL_DESARROLLADOR;
GRANT SELECT ON BDY1102_ET_FD.PROYECTO_INMOBILIARIO TO ROL_DESARROLLADOR;
GRANT SELECT ON BDY1102_ET_FD.PTJE_ANNOS_ANTIGUEDAD TO ROL_DESARROLLADOR;
GRANT SELECT ON BDY1102_ET_FD.PTJE_TIPO_PROPIEDAD TO ROL_DESARROLLADOR;
GRANT SELECT ON BDY1102_ET_FD.PTJE_TIPO_TRABAJADOR TO ROL_DESARROLLADOR;
GRANT SELECT ON BDY1102_ET_FD.REGION TO ROL_DESARROLLADOR;
GRANT SELECT ON BDY1102_ET_FD.SOLICITUD_CREDITO TO ROL_DESARROLLADOR;
GRANT SELECT ON BDY1102_ET_FD.SUCURSAL TO ROL_DESARROLLADOR;
GRANT SELECT ON BDY1102_ET_FD.TIPO_PROPIEDAD TO ROL_DESARROLLADOR;
GRANT SELECT ON BDY1102_ET_FD.TIPO_TRABAJADOR TO ROL_DESARROLLADOR;

GRANT SELECT, INSERT, UPDATE, DELETE ON BDY1102_ET_FD.DETALLE_PUNTAJE_SOLICITUD TO ROL_DESARROLLADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON BDY1102_ET_FD.RESULTADO_SOLICITUD TO ROL_DESARROLLADOR;

--- Usuario: BDY1102_ET_FD_DES ---------------------
-- BORRAR USUARIO:
--DROP USER BDY1102_ET_FD_DES CASCADE;

CREATE USER BDY1102_ET_FD_DES
IDENTIFIED BY "1234"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
;

-- Asignar cuota para el tablespace USERS (vistas)
ALTER USER BDY1102_ET_FD_DES QUOTA UNLIMITED ON USERS;

--- Permisos
-- Conexión a la DB
GRANT CREATE SESSION TO BDY1102_ET_FD_DES;

-- Permisos del caso
GRANT CREATE VIEW TO BDY1102_ET_FD_DES;
GRANT CREATE MATERIALIZED VIEW TO BDY1102_ET_FD_DES;

-- Asignamos el rol
GRANT ROL_DESARROLLADOR TO BDY1102_ET_FD_DES;

-- Permisos directos obligatorios
GRANT SELECT ON BDY1102_ET_FD.ANTECEDENTES_CLIENTE TO BDY1102_ET_FD_DES;
GRANT SELECT ON BDY1102_ET_FD.TIPO_TRABAJADOR TO BDY1102_ET_FD_DES;
GRANT SELECT ON BDY1102_ET_FD.ANTECEDENTES_LABORALES TO BDY1102_ET_FD_DES;
GRANT SELECT ON BDY1102_ET_FD.RESULTADO_SOLICITUD TO BDY1102_ET_FD_DES;
GRANT SELECT ON BDY1102_ET_FD.DETALLE_PUNTAJE_SOLICITUD TO BDY1102_ET_FD_DES;

-- Las instrucciones dicen que se deben TRUNCAR las tablas DETALLE_PUNTAJE_SOLICITUD
-- y RESULTADO_SOLICITUD. Ambas son de BDY1102_ET_FD, por lo tanto debemos dar
-- este permiso (a falta de un procedimiento almacenado): 
GRANT DROP ANY TABLE TO BDY1102_ET_FD_DES;

-- TIP:
-- ALTER SESSION SET CURRENT_SCHEMA = BDY1102_ET_FD;
-- ALTER SESSION SET CURRENT_SCHEMA = BDY1102_ET_FD_DES;
