CREATE TABLE IF NO EXISTS usuario (
    id_usuario BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(225) NOT NULL,
    role VARCHAR(50) NOT NULL,
    enable BOOLEAN NOT NULL DEFAULT TRUE
);